package bd.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Inkas generated by hbm2java
 */
@Entity
@Table(name = "INKAS")
public class Inkas implements java.io.Serializable {

	private static final long serialVersionUID = 189079480925407915L;
	private InkasId id;

	public Inkas() {
	}

	public Inkas(InkasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "datakey", column = @Column(name = "DATAKEY", nullable = false, length = 16)),
			@AttributeOverride(name = "operator", column = @Column(name = "OPERATOR", nullable = false, length = 32)),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", nullable = false, length = 32)),
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)),
			@AttributeOverride(name = "prava", column = @Column(name = "PRAVA", nullable = false, length = 10)),
			@AttributeOverride(name = "summ", column = @Column(name = "SUMM", precision = 15, scale = 0)),
			@AttributeOverride(name = "prim", column = @Column(name = "PRIM", length = 32)) })
	public InkasId getId() {
		return this.id;
	}

	public void setId(InkasId id) {
		this.id = id;
	}

}
