package bd.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InkasId generated by hbm2java
 */
@Embeddable
public class InkasId implements java.io.Serializable {

	private static final long serialVersionUID = -5664007739836554849L;
	private String datakey;
	private String operator;
	private String name;
	private Date dat;
	private String prava;
	private Double summ;
	private String prim;

	public InkasId() {
	}

	public InkasId(String datakey, String operator, String name, Date dat,
			String prava) {
		this.datakey = datakey;
		this.operator = operator;
		this.name = name;
		this.dat = dat;
		this.prava = prava;
	}

	public InkasId(String datakey, String operator, String name, Date dat,
			String prava, Double summ, String prim) {
		this.datakey = datakey;
		this.operator = operator;
		this.name = name;
		this.dat = dat;
		this.prava = prava;
		this.summ = summ;
		this.prim = prim;
	}

	@Column(name = "DATAKEY", nullable = false, length = 16)
	public String getDatakey() {
		return this.datakey;
	}

	public void setDatakey(String datakey) {
		this.datakey = datakey;
	}

	@Column(name = "OPERATOR", nullable = false, length = 32)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "NAME", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DAT", nullable = false, length = 19)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	@Column(name = "PRAVA", nullable = false, length = 10)
	public String getPrava() {
		return this.prava;
	}

	public void setPrava(String prava) {
		this.prava = prava;
	}

	@Column(name = "SUMM", precision = 15, scale = 0)
	public Double getSumm() {
		return this.summ;
	}

	public void setSumm(Double summ) {
		this.summ = summ;
	}

	@Column(name = "PRIM", length = 32)
	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InkasId))
			return false;
		InkasId castOther = (InkasId) other;

		return ((this.getDatakey() == castOther.getDatakey()) || (this
				.getDatakey() != null && castOther.getDatakey() != null && this
				.getDatakey().equals(castOther.getDatakey())))
				&& ((this.getOperator() == castOther.getOperator()) || (this
						.getOperator() != null
						&& castOther.getOperator() != null && this
						.getOperator().equals(castOther.getOperator())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getDat() == castOther.getDat()) || (this.getDat() != null
						&& castOther.getDat() != null && this.getDat().equals(
						castOther.getDat())))
				&& ((this.getPrava() == castOther.getPrava()) || (this
						.getPrava() != null && castOther.getPrava() != null && this
						.getPrava().equals(castOther.getPrava())))
				&& ((this.getSumm() == castOther.getSumm()) || (this.getSumm() != null
						&& castOther.getSumm() != null && this.getSumm()
						.equals(castOther.getSumm())))
				&& ((this.getPrim() == castOther.getPrim()) || (this.getPrim() != null
						&& castOther.getPrim() != null && this.getPrim()
						.equals(castOther.getPrim())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDatakey() == null ? 0 : this.getDatakey().hashCode());
		result = 37 * result
				+ (getOperator() == null ? 0 : this.getOperator().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getDat() == null ? 0 : this.getDat().hashCode());
		result = 37 * result
				+ (getPrava() == null ? 0 : this.getPrava().hashCode());
		result = 37 * result
				+ (getSumm() == null ? 0 : this.getSumm().hashCode());
		result = 37 * result
				+ (getPrim() == null ? 0 : this.getPrim().hashCode());
		return result;
	}

}
