package bd.domains;

// Generated 17.10.2012 8:37:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OperatorId generated by hbm2java
 */
@Embeddable
public class OperatorId implements java.io.Serializable {

	private static final long serialVersionUID = -8616298429276473893L;
	private String operid;
	private String operpass;
	private String name;
	private String prim;
	private String adr;
	private String tel;
	private String fio;
	private Short proc;

	public OperatorId() {
	}

	public OperatorId(String operid, String operpass, String name) {
		this.operid = operid;
		this.operpass = operpass;
		this.name = name;
	}

	public OperatorId(String operid, String operpass, String name, String prim,
			String adr, String tel, String fio, Short proc) {
		this.operid = operid;
		this.operpass = operpass;
		this.name = name;
		this.prim = prim;
		this.adr = adr;
		this.tel = tel;
		this.fio = fio;
		this.proc = proc;
	}

	@Column(name = "OPERID", nullable = false, length = 16)
	public String getOperid() {
		return this.operid;
	}

	public void setOperid(String operid) {
		this.operid = operid;
	}

	@Column(name = "OPERPASS", nullable = false, length = 16)
	public String getOperpass() {
		return this.operpass;
	}

	public void setOperpass(String operpass) {
		this.operpass = operpass;
	}

	@Column(name = "NAME", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRIM", length = 64)
	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	@Column(name = "ADR", length = 80)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Column(name = "TEL", length = 24)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FIO", length = 60)
	public String getFio() {
		return this.fio;
	}

	public void setFio(String fio) {
		this.fio = fio;
	}

	@Column(name = "PROC")
	public Short getProc() {
		return this.proc;
	}

	public void setProc(Short proc) {
		this.proc = proc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OperatorId))
			return false;
		OperatorId castOther = (OperatorId) other;

		return ((this.getOperid() == castOther.getOperid()) || (this
				.getOperid() != null && castOther.getOperid() != null && this
				.getOperid().equals(castOther.getOperid())))
				&& ((this.getOperpass() == castOther.getOperpass()) || (this
						.getOperpass() != null
						&& castOther.getOperpass() != null && this
						.getOperpass().equals(castOther.getOperpass())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getPrim() == castOther.getPrim()) || (this.getPrim() != null
						&& castOther.getPrim() != null && this.getPrim()
						.equals(castOther.getPrim())))
				&& ((this.getAdr() == castOther.getAdr()) || (this.getAdr() != null
						&& castOther.getAdr() != null && this.getAdr().equals(
						castOther.getAdr())))
				&& ((this.getTel() == castOther.getTel()) || (this.getTel() != null
						&& castOther.getTel() != null && this.getTel().equals(
						castOther.getTel())))
				&& ((this.getFio() == castOther.getFio()) || (this.getFio() != null
						&& castOther.getFio() != null && this.getFio().equals(
						castOther.getFio())))
				&& ((this.getProc() == castOther.getProc()) || (this.getProc() != null
						&& castOther.getProc() != null && this.getProc()
						.equals(castOther.getProc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOperid() == null ? 0 : this.getOperid().hashCode());
		result = 37 * result
				+ (getOperpass() == null ? 0 : this.getOperpass().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getPrim() == null ? 0 : this.getPrim().hashCode());
		result = 37 * result
				+ (getAdr() == null ? 0 : this.getAdr().hashCode());
		result = 37 * result
				+ (getTel() == null ? 0 : this.getTel().hashCode());
		result = 37 * result
				+ (getFio() == null ? 0 : this.getFio().hashCode());
		result = 37 * result
				+ (getProc() == null ? 0 : this.getProc().hashCode());
		return result;
	}

}
