package bd.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Operator generated by hbm2java
 */
@Entity
@Table(name = "OPERATOR", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class Operator implements java.io.Serializable {

	private static final long serialVersionUID = -6650224689162284844L;
	private String operid;
	private String operpass;
	private String name;
	private String prim;
	private String adr;
	private String tel;
	private String fio;
	private Short proc;

	public Operator() {
	}

	public Operator(String operid, String operpass, String name) {
		this.operid = operid;
		this.operpass = operpass;
		this.name = name;
	}

	public Operator(String operid, String operpass, String name, String prim, String adr, String tel, String fio, Short proc) 
	{
		this.operid = operid;
		this.operpass = operpass;
		this.name = name;
		this.prim = prim;
		this.adr = adr;
		this.tel = tel;
		this.fio = fio;
		this.proc = proc;
	}

	public Operator(String string, String string2, String string3, short s) 
	{
		this.operid = string;
		this.operpass = string2;
		this.name = string3;
		this.proc = s;
	}

	@Id
	@Column(name = "OPERID", unique = true, nullable = false, length = 16)
	public String getOperid() {
		return this.operid;
	}

	public void setOperid(String operid) {
		this.operid = operid;
	}

	@Column(name = "OPERPASS", nullable = false, length = 16)
	public String getOperpass() {
		return this.operpass;
	}

	public void setOperpass(String operpass) {
		this.operpass = operpass;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRIM", length = 64)
	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	@Column(name = "ADR", length = 80)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Column(name = "TEL", length = 24)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FIO", length = 60)
	public String getFio() {
		return this.fio;
	}

	public void setFio(String fio) {
		this.fio = fio;
	}

	@Column(name = "PROC")
	public Short getProc() {
		return this.proc;
	}

	public void setProc(Short proc) {
		this.proc = proc;
	}

}
