package bd.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Polzov generated by hbm2java
 */
@Entity
@Table(name = "POLZOV")
public class Polzov implements java.io.Serializable {

	private static final long serialVersionUID = 4513970710097790532L;
	private String userid;
	private String userpass;
	private String username;
	private String arm;
	private String rasr;
	private String operator;

	public Polzov() {
	}

	public Polzov(String userid, String userpass, String arm, String rasr,
			String operator) {
		this.userid = userid;
		this.userpass = userpass;
		this.arm = arm;
		this.rasr = rasr;
		this.operator = operator;
	}

	public Polzov(String userid, String userpass, String username, String arm,
			String rasr, String operator) {
		this.userid = userid;
		this.userpass = userpass;
		this.username = username;
		this.arm = arm;
		this.rasr = rasr;
		this.operator = operator;
	}

	public Polzov(String operatorName) {
		// TODO Auto-generated constructor stub
		this.username=operatorName;
	}

	@Id
	@Column(name = "USERID", unique = true, nullable = false, length = 16)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "USERPASS", nullable = false, length = 16)
	public String getUserpass() {
		return this.userpass;
	}

	public void setUserpass(String userpass) {
		this.userpass = userpass;
	}

	@Column(name = "USERNAME", length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "ARM", nullable = false, length = 16)
	public String getArm() {
		return this.arm;
	}

	public void setArm(String arm) {
		this.arm = arm;
	}

	@Column(name = "RASR", nullable = false, length = 16)
	public String getRasr() {
		return this.rasr;
	}

	public void setRasr(String rasr) {
		this.rasr = rasr;
	}

	@Column(name = "OPERATOR", nullable = false, length = 32)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
